version: '3.9'
networks:
  losst-network:
volumes:
    losst-vl:
services:
    docker-nginx:
      image: nginx
      ports:
         - '8094:80'
      volumes:  
         - ./html:/var/www/html/
         - ./nginx:/etc/nginx/conf.d
      networks:
         - losst-network
    docker-mysql:
      image: mysql
      volumes:
        - losst-vl:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=database
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      networks:
        - losst-network
    docker-phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
        - "8095:80"
      environment:
        - PMA_HOST=docker-mysql
      networks:
        - losst-network
    docker-php-fpm:
      build: 
        context: ./php-fpm
      volumes:
        - ./:/var/www/
      networks:
        - losst-network
